api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import DishModelViewSet, BasketModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'dishes', DishModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

dishes/urls.py
from django.urls import path

from dishes.views import MenuView, CategoryListView, basket_add, basket_remove

app_name = 'dishes'

urlpatterns = [
    path('', MenuView.as_view(), name='menu'),
    path('category/<slug:category_slug>/', CategoryListView.as_view(), name='category'),
    path('page/<int:page>/', MenuView.as_view(), name='paginator'),
    path('add/<int:dish_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order-create'),
    path('order-success/', SuccessTemplateView.as_view(), name='order-success'),
    path('order-cancel/', CancelTemplateView.as_view(), name='order-cancel'),
    path('', OrderListView.as_view(), name='orders-list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),

]

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from dishes.views import IndexView, update_basket_quantity, pageNotFound
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('menu/', include('dishes.urls', namespace='dishes')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token),
    path('update_basket_quantity/<int:basket_id>/', update_basket_quantity, name='update_basket_quantity'),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = pageNotFound

users/urls.py
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView,
                         UserRegisterView, BasketView, logout, ReservationView, ReservationVerificationView, UserProfileView)

app_name = 'users'

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('email_verification/<str:email>/<uuid:unique_code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('reservation/', ReservationView.as_view(), name='reservation'),
    path('reservation_verification', ReservationVerificationView.as_view(), name='reservation_verification'),
    path('profile/', UserProfileView.as_view(), name='profile')
]

dishes/models.py
import stripe
from django.conf import settings
from django.db import models
from django.urls import reverse

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class DishCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} | {self.description}'

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('dishes:category', kwargs={'category_slug': self.slug})


class Dish(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=3)
    weight = models.IntegerField(blank=True, null=True)
    image = models.ImageField(upload_to='dishes_images', blank=True)
    category = models.ForeignKey(to=DishCategory, on_delete=models.CASCADE)
    stripe_price_id = models.CharField(max_length=128, null=True, blank=True)

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

    def __str__(self):
        return f'Блюдо: {self.name} | Категория: {self.category.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_price_id = stripe_product_price['id']
        super(Dish, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='rub')
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.dish.stripe_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    dish = models.ForeignKey(to=Dish, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзину пользователей'
        verbose_name_plural = 'Корзина пользователей'

    def __str__(self):
        return f'Корзина для {self.user} | Блюдо: {self.dish.name}'

    def sum(self):
        return self.dish.price * self.quantity

    def de_json(self):
        basket_item = {
            'dish_name': self.dish.name,
            'quantity': self.quantity,
            'price': float(self.dish.price),
            'sum': float(self.sum())
        }
        return basket_item

    @classmethod
    def add_or_update_basket(cls, dish_id, user):
        baskets = Basket.objects.filter(user=user, dish_id=dish_id)

        if not baskets.exists():
            obj = Basket.objects.create(user=user, dish=dish_id, quantity=1)
            is_created = True
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
            is_created = False
            return basket, is_created





dishes/views.py
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse, HttpResponseNotFound
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.views import View
from django.views.generic import ListView

from dishes.models import Basket, Dish, DishCategory


class IndexView(ListView):
    active_section = 'index'
    template_name = 'dishes/index.html'
    model = Dish
    context_object_name = 'dishes'
    extra_context = {'title': "Главная страница"}

    def get_queryset(self):
        return Dish.objects.all().order_by('-id')[:3]


class MenuView(ListView):
    model = Dish
    template_name = 'dishes/menu.html'
    context_object_name = 'dishes'
    paginate_by = 9
    extra_context = {'title': "Меню"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = DishCategory.objects.all()
        return context


class CategoryListView(View):
    template_name = 'dishes/menu.html'

    def get(self, request, category_slug):
        dishes = Dish.objects.filter(category__slug=category_slug)
        categories = DishCategory.objects.all()

        context = {
            'dishes': dishes,
            'categories': categories,
        }

        return render(request, self.template_name, context=context)


@login_required
def basket_add(request, dish_id):
    dish = Dish.objects.get(id=dish_id)
    Basket.add_or_update_basket(dish, request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def update_basket_quantity(request, basket_id):
    basket = get_object_or_404(Basket, id=basket_id)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))
        basket.quantity = quantity
        basket.total_price = int(basket.sum())
        basket.save()

        baskets = Basket.objects.filter(user=request.user)
        total_quantity = baskets.total_quantity()
        total_price_sum = int(baskets.total_sum())

        response_data = {
            'message': 'Количество блюд и итоговая цена успешно обновлены',
            'quantity': basket.quantity,
            'total_price_item': basket.total_price,
            'total_quantity': total_quantity,
            'total_price_sum': total_price_sum,
        }
        return JsonResponse(response_data)

    response_data = {'error': 'Произошла ошибка при обновлении количества блюд и итоговой цены'}
    return JsonResponse(response_data, status=400)


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена!</h1>')




dishes/templates/dishes/base.html
<!DOCTYPE HTML>
{% load static %}
{% include 'dishes/navigation.html' %}

<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ title }}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="freehtml5.co" />

	<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:300,300i,400,400i,500,600i,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/menu.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
	<div id="page">
	<header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner" style="background-image: url(/static/images/a_cup.jpg);" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<div class="display-t js-fullheight">
						<div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
							{% block inscription %} {% endblock %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
{% block content %} {% endblock %}
	<div id="fh5co-started" class="fh5co-section animate-box" style="background-image: url(/static/images/hero_1.jpeg);" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<p><a href="{% url 'users:reservation' %}" class="btn btn-primary btn-outline">Забронировать</a></p>
				</div>
			</div>
		</div>
	</div>
	<footer id="fh5co-footer" role="contentinfo" class="fh5co-section">
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-4 fh5co-widget">
					<h4>Ресторан</h4>
					<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
				</div>

				<div class="col-md-2 col-md-push-1 fh5co-widget">
					<h4>Ссылки</h4>
					<ul class="fh5co-footer-links">
						<li><a href="\">Главная</a></li>
						<li><a href="{% url 'dishes:menu' %}">Меню</a></li>
					</ul>
				</div>

				<div class="col-md-4 col-md-push-1 fh5co-widget">
					<h4>Дополнительная информация</h4>
					<ul class="fh5co-footer-links">
						<li>--------------<br>--------------</li>
						<li><a href="#">--------------</a></li>
						<li><a href="#">--------------</a></li>
						<li><a href="#">--------------</a></li>
					</ul>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2023 All Rights Reserved.</small>
					</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="#"><i class="icon-twitter2"></i></a></li>
							<li><a href="#"><i class="icon-facebook2"></i></a></li>
							<li><a href="#"><i class="icon-linkedin2"></i></a></li>
							<li><a href="#"><i class="icon-dribbble2"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>
	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up22"></i></a>
	</div>
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>
	<div class="gototop js-top">
		<a href="##" class="js-gotop"><i class="icon-arrow-up22"></i></a>
	</div>
</body>
</html>

dishes/templates/dishes/basket.html
{% load static %}
{% load humanize %}

{% if baskets %}
    <head>
        <link rel="stylesheet" href="{% static 'css/basket.css' %}">
        <title>{{ title }}</title>
    </head>
    <div class="wrap cf">
      <h1 class="projTitle">Моя корзина</h1>
      <div class="heading cf">
        <a href="{% url 'dishes:menu' %}" class="continue">Вернуться в меню</a>
      </div>
      <div class="cart-wrap">
        <div class="cart">
          <ul class="cart-items">
            {% for basket in baskets %}
            <li class="cart-item" data-basket-id="{{ basket.id }}">
              <div class="item-info">
                <div class="item-img">
                  <img src="{{ basket.dish.image.url }}" alt="image not found" class="itemImg" />
                </div>
                  <div class="item-details">
                    <h3>{{ basket.dish.name }}</h3>
                    <div class="item-quantity">
                      <input type="number" class="qty update-quantity" min="1" max="10" value="{{ basket.quantity }}" data-basket-id="{{ basket.id }}" />
                    </div>
                    <div class="item-total" data-basket-id="{{ basket.id }}">
                      <p class="item-price item-price-{{ basket.id }}">{{ basket.sum|floatformat:"0"|intcomma }} руб.</p>
                    </div>
                  </div>
              </div>
              <form method="POST" action="{% url 'dishes:basket_remove' basket.id %}">
                {% csrf_token %}
                <button type="submit" class="remove">Удалить</button>
              </form>
            </li>
            {% endfor %}
          </ul>
        </div>

        <div class="cart-total">
          <div class="total-row">
            <span class="label">Общее кол-во:</span>
            <span class="value total-quantity">{{ baskets.total_quantity }} шт.</span>
          </div>
          <div class="total-row final">
            <span class="label">Всего:</span>
            <span class="value total-price">{{ baskets.total_sum|floatformat:"0"|intcomma }} руб.</span>
          </div>
          <div class="order-button">
            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order-create' %}">
                Оформить заказ
            </a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/basket.js' %}"></script>
{% else %}
<h4 class="mt-3 mb-3 text-center">
    Корзина пуста
</h4>
<a href="{% url 'dishes:menu' %}" class="continue">Вернуться в меню</a>
{% endif %}

dishes/templates/dishes/index.html
{% extends 'dishes/base.html' %}
{% load humanize %}
{% load static %}

{% block inscription %}
	<h1>Ресторан</h1>
{% endblock %}

{% block content %}
<div id="fh5co-slider" class="fh5co-section animate-box">
	<div class="container">
		<div class="row">
			<div class="col-md-6 animate-box">
				<div class="fh5co-heading">
					<h2>Новинки меню</h2>
				</div>
			</div>
			<div class="col-md-6 col-md-push-1 animate-box">
				<aside id="fh5co-slider-wrwap">
				<div class="flexslider">
					{% for dish in dishes %}
						<ul class="slides">
						<li style="background-image: url({{ dish.image.url }});">
							<div class="overlay-gradient"></div>
							<div class="container-fluid">
								<div class="row">
									<div class="col-md-12 col-md-offset-0 col-md-pull-10 slider-text slider-text-bg">
										<div class="slider-text-inner">
											<div class="desc">
												<span class="fh5co-price">{{ dish.name }}</span>
												<p class="ingredients">{{ dish.description }}</p>
												<span class="dish-weight">{{ dish.weight }} г /</span>
												<span class="fh5co-price">{{ dish.price|floatformat:"0"|intcomma }} руб.<sup></sup></span>
											</div>
											<a class="dish-button"
											   href="{% url 'dishes:basket_add' dish.id %}">
												Добавить в корзину
											</a>
										</div>
									</div>
								</div>
							</div>
						</li>
						</ul>
					{% endfor %}
				</div>
				</aside>
			</div>
		</div>
	</div>
</div>

<div id="fh5co-about" class="fh5co-section">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-pull-4 img-wrap animate-box" data-animate-effect="fadeInLeft">
				<img src="/static/images/interior-cafe-bar-kafe-bar.jpg" alt="image error">
			</div>
			<div class="col-md-5 col-md-push-1 animate-box">
				<div class="section-heading">
					<h2>Ресторан</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae neque quisquam at deserunt ab praesentium architecto tempore saepe animi voluptatem molestias, eveniet aut laudantium alias, laboriosam excepturi, et numquam? Atque tempore iure tenetur perspiciatis, aliquam, asperiores aut odio accusamus, unde libero dignissimos quod aliquid neque et illo vero nesciunt. Sunt!</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam iure reprehenderit nihil nobis laboriosam beatae assumenda tempore, magni ducimus abentey.</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

dishes/templates/dishes/menu.html
{% extends 'dishes/base.html' %}
{% load static %}
{% load cache %}
{% load humanize %}

{% block inscription %}
	<h1>Меню</h1>
{% endblock %}

{% block content %}
	<div id="fh5co-featured-menu" class="fh5co-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12 fh5co-heading animate-box">
					<h1 class="menu-text">Меню ресторана</h1>
				</div>
				<div class="all-menu">
					<div class="all-dishes">
						<li><a href="{% url 'dishes:menu' %}">Все блюда</a></li>
					</div>
					{% for category in categories %}
						<div class="categories">
							<li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
						</div>
					{% endfor %}
				</div>
				<div class="row">
                    {% for dish in dishes %}
                        <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="{{ dish.image.url }} "
                                     alt="image-error">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
									<h3 class="fh5co-price">{{ dish.name }}</h3>
                                    <h2>{{ dish.description }}</h2>
                                </h4>
                                <span class="fh5co-price">{{ dish.price|floatformat:"0"|intcomma }} руб. /<sup></sup></span>
								<span class="fh5co-price">{{ dish.weight }} г<sup></sup></span>-->
                            </div>
                            <div class="card-footer text-center">
                                <a class="btn btn-outline-success"
                                   href="{% url 'dishes:basket_add' dish.id %}">
                                    Отправить в корзину
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
            	</div>
				{% if is_paginated %}
					<nav aria-label="Page navigation example">
						<ul class="pagination justify-content-center">
							<li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
								<a class="page-link"
								   href="{% if page_obj.has_previous %} {% url 'dishes:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
								   tabindex="-1" aria-disabled="true">
									Предыдущая
								</a>
							</li>
							{% for page in paginator.page_range %}
								<li class="page-item">
									<a class="page-link" href="{% url 'dishes:paginator' page %}">
									{{ page }}
									</a>
								</li>
							{% endfor %}
							<li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
								<a class="page-link"
								   href="{% if page_obj.has_next %} {% url 'dishes:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
									Следующая
								</a>
							</li>
						</ul>
					</nav>
            	{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

dishes/templates/dishes/navigation.html
{% load static %}
<nav class="fh5co-nav" role="navigation">
     <div class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center logo-wrap">
                    <div id="fh5co-logo"><a href="index.html">Ресторан<span>.</span></a></div>
                </div>
                <div class="col-xs-12 text-center menu-1 menu-wrap">
                    <ul>
                        <li {% if request.resolver_match.view_name == 'index' %}class="active"{% endif %}><a href="{% url 'index' %}">Главная</a></li>
                        <li {% if request.resolver_match.view_name == 'dishes:index' %}class="active"{% endif %}><a href="{% url 'dishes:menu' %}">Меню</a></li>
                        <li {% if request.resolver_match.view_name == 'users:reservation' %}class="active"{% endif %}><a href="{% url 'users:reservation' %}">Бронирование</a></li>
                        <li><a href="contact.html">Контакты</a></li>
                        {% if user.is_authenticated %}
                            <li class="has-dropdown">
                                <a href="{% url 'users:profile' %}">{{ user.username }}</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'users:basket' %}">Корзина</a></li>
                                    <li><a href="{% url 'orders:orders-list' %}">Мои заказы</a></li>
                                    <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="has-dropdown">
                                <a href="{% url 'users:login' %}">Войти</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'users:register' %}">Создать учетную запись</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
     </div>
</nav>